import Mock from 'mockjs'

export default{
    getMenu:config=>{
        const {username,password}=JSON.parse(config.body)
        //判断用户是否存在
        //判断账号和密码是否对应
        if(username==='admin'&&password==='admin'){
            return {
                code:20000,
                data:{
                    menu:[
                        {
                          path:'/home',
                          name:'home',
                          lable:'首页',
                          icon:'s-home',
                          url:'home/index'
                        },
                        {
                          lable:'其他',
                          icon:'location',
                          children:[
                            {
                              path:'/page1',
                              name:'page1',
                              lable:'页面1',
                              icon:'setting',
                              url:'Other/pageone.vue'
                            },
                            {
                              path:'/page2',
                              name:'page2',
                              lable:'页面2',
                              icon:'setting',
                              url:'Other/pagetwo.vue'
                            },
                          ]
                        },
                        {
                          path:'/mail',
                          name:'mail',
                          lable:'商品管理',
                          icon:'video-play',
                          url:'Mail/index'
                        },
                        {
                          path:'/user',
                          name:'user',
                          lable:'用户管理',
                          icon:'user',
                          url:'User/index'
                        },
                    ]
                },
                token:Mock.Random.guid(),
                message:'获取成功'
            }
        }else if(username==='xiaoxiao'&&password==='xiaoxiao'){
            return {
                code:20000,
                data:{
                    menu:[
                        {
                          path:'/home',
                          name:'home',
                          lable:'首页',
                          icon:'s-home',
                          url:'home/index'
                        },
                        {
                          path:'/mail',
                          name:'mail',
                          lable:'商品管理',
                          icon:'video-play',
                          url:'Mail/index'
                        },
                    ],
                    token:Mock.Random.guid(),
                    message:'获取成功'
                }
            }
        }else{
            return {
                code:-999,
                data:{
                    message:'密码错误'
                }
            }
        }
    }
}